[package]
name = "qrfs_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"
thiserror =  "1"
qrcode = "0.14"
image = "0.25"
rqrr = "0.10.0"
fuser = "0.16.0"
libc = "0.2"
base64 = "0.22.1"