[package]
name = "qrfs_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
qrfs_core = { path = "../qrfs_core" }
fuse3 = { version = "0.8", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
bincode = "1"